package com.example.accessingdatamysql.myorg;

import com.example.accessingdatamysql.org.Organization;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;

@CrossOrigin
@RestController // This means that this class is a Controller
@RequestMapping(path="/myorg") // This means URL's start with /orgauth (after Application path)
public class OrgRosterController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OrgRosterRepository orgRosterRepository;

    @Autowired
    private MyOrgRosterRepository myOrgRosterRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<OrganizationRoster> getOrgs()
    {
        return myOrgRosterRepository.findAll();
    }

    @PostMapping(path="/user")
    public @ResponseBody Map<String, Object> getUsersOrgs(@RequestBody Map<String, String> json)
    {
        Map<String, Object> response = new HashMap<>();
//        System.out.println(json.entrySet());
        if (json.containsKey("email"))
        {
            response.put("result", "success");
            response.put("data", myOrgRosterRepository.findUserOrgs(json.get("email")));
            return response;
        }
        response.put("result", "failure - bad request");
        return response;
    }
}

